# Generated by Django 5.2.6 on 2026-02-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprofile',
            name='locations',
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='nearby_locations',
            field=models.ManyToManyField(blank=True, related_name='nearby_models', to='models_app.location'),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='primary_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_models', to='models_app.location'),
        ),
    ]
