# Generated by Django 5.2.6 on 2026-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_county_locationgroup_location_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprofile',
            name='model_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
