# Generated by Django 5.2.6 on 2026-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_alter_modelprofile_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
