# Generated by Django 5.2.11 on 2026-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_modelprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='short_summary',
            field=models.CharField(default='Discover my profile', max_length=40),
        ),
    ]
