import os
import json
from django.core.management.base import BaseCommand
from django.conf import settings
from apps.models_app.models.location import County, LocationGroup, Location
from apps.models_app.models.service import Service


class Command(BaseCommand):
    help = 'Seeds the database with data extracted from nairobihot.com.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--file',
            type=str,
            default='data/raw/nairobihot_data.json',
            help='Path to the JSON file generated by the scraper.'
        )

    def handle(self, *args, **options):
        file_path = options['file']
        
        # Resolve absolute path based on project root if it's relative
        if not os.path.isabs(file_path):
            file_path = os.path.join(settings.BASE_DIR, file_path)

        if not os.path.exists(file_path):
            self.stdout.write(self.style.ERROR(f'File not found: {file_path}. Please run the scraper first.'))
            return

        self.stdout.write(self.style.WARNING(f'Loading data from {file_path}...'))
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except json.JSONDecodeError as e:
            self.stdout.write(self.style.ERROR(f'Failed to parse JSON file: {e}'))
            return

        locations_data = data.get('locations', [])
        services_data = data.get('services', [])

        # Process Services
        self.stdout.write(self.style.SUCCESS(f'Processing {len(services_data)} services...'))
        services_created = 0
        for service_name in services_data:
            obj, created = Service.objects.get_or_create(name=service_name)
            if created:
                services_created += 1

        self.stdout.write(self.style.SUCCESS(f'Created {services_created} new Services.'))

        # Process Locations
        self.stdout.write(self.style.SUCCESS(f'Processing {len(locations_data)} locations...'))
        locations_created = 0
        counties_created = 0
        groups_created = 0
        
        for loc in locations_data:
            county_name = loc.get('county', 'Other Regions')
            group_name = loc.get('group', 'General')
            location_name = loc.get('name')
            
            if not location_name:
                continue
                
            # Normalize location name to Title Case to prevent slug conflicts from case variations
            location_name = location_name.strip().title()

            # 1. Get or Create County
            county_obj, created = County.objects.get_or_create(name=county_name)
            if created:
                counties_created += 1

            # Create a unique group name per county to avoid slug conflicts
            if group_name == 'General':
                group_name = f"{county_name} - General"

            # 2. Get or Create Group
            group_obj, created = LocationGroup.objects.get_or_create(
                name=group_name, 
                county=county_obj
            )
            if created:
                groups_created += 1

            # 3. Get or Create Location
            from django.db import IntegrityError
            try:
                location_obj, created = Location.objects.get_or_create(
                    name=location_name,
                    defaults={'group': group_obj, 'is_primary': False}
                )
                if created:
                    locations_created += 1
                elif location_obj.group != group_obj:
                    # If the location exists but under a different group, update it if necessary, 
                    # but typically get_or_create handles initial creation. We won't overwrite existing manually.
                    pass
            except IntegrityError:
                # This happens if there's a name variation that generates the same slug, 
                # e.g., 'Ngong' vs 'Ngong ' vs 'Ngong-Road' (if slugified similarly)
                self.stdout.write(self.style.WARNING(f"Skipped duplicate/conflicting location: {location_name}"))

        self.stdout.write(self.style.SUCCESS(f'Seeding Complete!'))
        self.stdout.write(self.style.SUCCESS(f'  Counties Created: {counties_created}'))
        self.stdout.write(self.style.SUCCESS(f'  Groups Created: {groups_created}'))
        self.stdout.write(self.style.SUCCESS(f'  Locations Created: {locations_created}'))
